services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciador_pagamentos
      MYSQL_USER: gerenciador_pagamentos
      MYSQL_PASSWORD: "123456@@"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: gerenciador-pagamentos-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=your-app-key-here
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=gerenciador_pagamentos
      - DB_PASSWORD=123456@@
      - DB_DATABASE=gerenciador_pagamentos
      - GATEWAY1_URL=http://gateways-mock:3001
      - GATEWAY2_URL=http://gateways-mock:3002
    ports:
      - "3333:3333"
    depends_on:
      mysql:
        condition: service_healthy
      gateways-mock:
        condition: service_started
    volumes:
      - ./tmp:/app/tmp

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: gateways-mock
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
